export { loopSteps } from './content.js';

export const principles = [
  {
    id: 'model', title: 'Give every connection a meaning', category: '01 / MODEL THE RELATIONSHIPS', status: 'documented', form: 'FOUNDATION',
    definition: 'A graph represents things as nodes and relationships as edges. Here, graph engineering means choosing those things, defining exactly what connects them, and using that structure to make decisions or check results.',
    analogy: 'On a street map, a dot can mean a place and a line can mean a road. In a review, the dots are checks and the arrows mean “send this result to the next step.”',
    why: 'A diagram becomes useful when its connections answer a real question. Different edge meanings require different rules: a road you can travel is different from a task you must finish first.',
    application: 'Kiran’s Warsaw project used several relationship models: walkable places linked for routefinding, projects linked by build references, parent objects containing child objects, and review results flowing into a decision. These were different graphs serving different jobs.',
    when: 'Use this when relationships affect the answer: what can reach what, what depends on what, or which results must arrive before a decision. Name the node type and edge meaning first.',
    limit: '“Graph engineering” is used here as a descriptive engineering approach. The inspected material does not establish one unified knowledge graph covering the entire development process.',
    nodes: ['Places', 'Walkable connection', 'Other places'], source: 'graph-model',
  },
  {
    id: 'dependencies', title: 'Put prerequisites before consumers', category: '02 / DEPENDENCY ORDER', status: 'documented', form: 'EXPLICIT CONFIGURATION',
    definition: 'A dependency graph says which part needs another part. An arrow from a prerequisite to its consumer means “this must be available first.” An acyclic graph has no chain that circles back to itself.',
    analogy: 'You need a foundation before you build the walls. Making the foundation depend on the walls would create an impossible circular prerequisite.',
    why: 'Dependencies explain the order of work and which downstream parts deserve checking after an upstream change.',
    application: 'The inspected TypeScript configuration gives the client a reference to shared code. The server references both shared and client projects. The root typecheck uses TypeScript build mode, which understands these project references.',
    when: 'Use this for multi-part builds, data pipelines or tasks with prerequisites. Check for circular dependencies, and identify the consumers affected by a change.',
    limit: 'These references document a build structure. They do not establish a measured speedup, a custom graph scheduler, or that the live server imports the entire client.',
    nodes: ['Shared', 'Client', 'Server'], source: 'graph-build',
  },
  {
    id: 'review', title: 'Branch out, then join the results', category: '03 / FAN-OUT & FAN-IN', status: 'documented', form: 'CONTROL-FLOW PATTERN',
    definition: 'Fan-out sends one task into several independent checks. Fan-in brings their results together before a shared decision. A join is a point that waits for the required branches.',
    analogy: 'A building inspection can include separate structural, electrical and fire checks. The final decision needs their results together.',
    why: 'Different checks ask different questions. A join brings required results together. Completeness checks catch missing branches, and duplicate handling combines overlapping findings.',
    application: 'The fresh-review workflow runs separate review lenses in parallel, waits for them, combines overlapping findings, then sends candidates to skeptic checks. It keeps evidence of failed reviewers instead of treating silence as “no bugs.”',
    when: 'Use this when checks can run independently but their outputs must feed one decision. Define required branches, failure handling, and how duplicates are recognized.',
    limit: 'This is implemented branching and joining in workflow code. It is not evidence of a generic graph-orchestration framework. Duplicate detection is a heuristic, and reviewers can still miss or invent problems.',
    nodes: ['Changed code', 'Review lenses', 'Join findings', 'Challenge findings'], source: 'fresh',
  },
  {
    id: 'gates', title: 'Make the final node enforce a rule', category: '04 / GATES & COMPLETENESS', status: 'observed', form: 'CODE + RECORDED CORRECTION',
    definition: 'A gate is a decision point with explicit conditions. It asks whether the evidence arriving from earlier steps is sufficient to allow the work to proceed.',
    analogy: 'An inspector cannot sign off a building because one required inspection report never arrived.',
    why: 'Successful individual branches do not imply a complete workflow. Missing evidence and a confirmed serious defect need distinct outcomes.',
    application: 'A sampled review found that the Warsaw review system itself needed stricter handling of incomplete output. The corrected gate blocks confirmed serious findings and reports an error for incomplete required checks. A complete review can still contain uncertainty.',
    when: 'Use this before merging, releasing, importing assets or making other decisions that depend on multiple checks. State what passes, what blocks, and what counts as incomplete.',
    limit: 'The interaction below models two conditions. The actual gate also examines verifier results and serious unverified findings. PASS is a workflow outcome, not proof that the code is bug-free.',
    nodes: ['Required results', 'Gate rules', 'PASS / BLOCK / ERROR'], source: 'gate',
  },
  {
    id: 'navigation', title: 'Find routes through valid connections', category: '05 / CONNECTIVITY & SEARCH', status: 'documented', form: 'EXPLICIT GRAPH IN CODE',
    definition: 'A path is a sequence of connected nodes. Routefinding searches for a useful path, considering which connections are allowed and what they cost. Connectivity asks whether a route exists at all.',
    analogy: 'A satnav needs usable roads, not just two addresses. Closing a bridge can change the route or make the destination unreachable.',
    why: 'A destination can be close in a straight line but unreachable through valid connections. Search also needs a limit so it cannot consume unlimited work.',
    application: 'Warsaw’s navigation code stores nodes with neighbor links and checks potential connections against the physics world. Bots use A* (“A-star”): search prioritizes cost so far plus an estimate of cost ahead. It can expand at most 4,000 nodes—inspect their outgoing connections—per search. Results distinguish complete and partial routes to selected graph nodes.',
    when: 'Use this for movement, network routing or reachability questions. Validate edges against the real rules, handle disconnected destinations, and state the search budget.',
    limit: 'A complete result reaches the selected graph destination; it does not prove access to every possible world position. A budget or disconnected graph can produce a partial route. These source reads do not certify current gameplay.',
    nodes: ['Start', 'Valid links', 'Selected destination'], source: 'graph-nav',
  },
  {
    id: 'hierarchy', title: 'Let related objects move together', category: '06 / TREES & LOCAL TRANSFORMS', status: 'documented', form: 'EXPLICIT SCENE HIERARCHY',
    definition: 'A tree is a connected graph without cycles. In a rooted scene hierarchy, each child has one parent, and its position and rotation are interpreted relative to that parent.',
    analogy: 'Move your shoulder and the arm moves with it. The hand can still move relative to the arm.',
    why: 'Parent-child relationships let a complex object move coherently without separately calculating every part’s final position.',
    application: 'The inspected Three.js partner view creates group, figure, body and shoulder objects. The upper arm, hand and blade are attached to the shoulder; the shoulder is attached to the body, which belongs to the figure and outer group.',
    when: 'Use this for articulated characters, vehicles or cameras whose parts should inherit movement. Choose parents that match the intended movement.',
    limit: 'A scene hierarchy organizes transforms. It does not by itself define collision, network ownership or intelligent decisions, and it is a different graph from navigation.',
    nodes: ['Group', 'Figure', 'Body', 'Shoulder', 'Hand + blade'], source: 'graph-scene',
  },
  {
    id: 'provenance', title: 'Trace an output back to its inputs', category: '07 / PROVENANCE & INVALIDATION', status: 'documented', form: 'DEPENDENCY CHECKS',
    definition: 'Provenance records where an output came from. Invalidation means marking that output as needing replacement when the inputs it depends on have changed.',
    analogy: 'A printed map belongs to a particular version of the streets. A new road layout can make that map stale.',
    why: 'An old generated asset can look convincing while no longer matching the current world. A fingerprint identifies a version; it cannot judge appearance.',
    application: 'The market lighting installer checks the source-file fingerprints, scene metadata and texture bytes. A changed source is rejected with instructions to re-export and rebake. Runtime code separately checks that the lighting asset matches the layout and scene.',
    when: 'Use this for generated lighting, cached calculations, compiled assets or data reports. Record the relevant inputs, detect changes, and define how stale outputs are rebuilt.',
    limit: 'These are graph-like dependency contracts implemented with fingerprints and checks. They do not establish a knowledge-graph database, prove a cloud bake succeeded, or prove that the lighting looks good.',
    nodes: ['Source files', 'Exported scene', 'Baked lighting', 'Compatibility check'], source: 'graph-assets',
  },
  {
    id: 'feedback', title: 'Use a cycle to learn from results', category: '08 / FEEDBACK & STOP CONDITIONS', status: 'observed', form: 'RECORDED ITERATION',
    definition: 'A cycle returns to an earlier step. A feedback cycle uses the result of an action to decide what to change next. It needs a checkable goal and a way to stop.',
    analogy: 'A builder checks a fitted door, adjusts the hinge, and checks again until it closes properly.',
    why: 'A strictly one-way sequence cannot respond to an unexpected result. Repeating without a new observation or stop condition can waste work instead of improving it.',
    application: 'The Palace column episode went from a visual problem to geometry inspection, a bounded correction and further checks: the grooves had been hidden behind flat panels. The handoff protocol also documents another repair round when checks fail or serious findings remain.',
    when: 'Use this when quality must be discovered through testing or observation. Define the expected result, retain the evidence, bound retries, and escalate when progress stalls.',
    limit: 'The column correction is supported by sampled records. The broader repair-loop policy is documented separately. Iteration is not proof of model retraining or a guarantee of convergence.',
    nodes: ['Observe', 'Investigate', 'Change', 'Check', 'Observe again'], source: 'graph-feedback',
  },
];
